// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['collections/backgrounds'], function(BackgroundsCollection) {
    var Background, _ref;
    return Background = (function(_super) {
      __extends(Background, _super);

      function Background() {
        _ref = Background.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Background.prototype.el = "body";

      Background.prototype.initialize = function(app) {
        return this.collection = new BackgroundsCollection(app.backgrounds);
      };

      Background.prototype.render = function() {
        var model;
        model = this.collection.findWhere({
          active: true
        });
        this.model = model;
        return this.$el.css("background", 'url("' + model.toJSON().url + '")');
      };

      Background.prototype.changeBackground = function(model) {
        this.collection.findWhere({
          active: true
        }).set({
          active: false
        });
        this.collection.findWhere({
          url: model.toJSON().url
        }).set({
          active: true
        });
        this.model = model;
        return this.render();
      };

      Background.prototype.random = function() {
        var model, number;
        number = Math.floor(Math.random() * this.collection.length);
        model = this.collection.at(number);
        if (model.toJSON().url !== this.model.toJSON().url) {
          return this.changeBackground(model);
        }
      };

      return Background;

    })(Backbone.View);
  });

}).call(this);
