// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['text!templates/header.html'], function(t) {
    var HeaderView, _ref;
    return HeaderView = (function(_super) {
      __extends(HeaderView, _super);

      function HeaderView() {
        _ref = HeaderView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      HeaderView.prototype.el = "#advert_text";

      HeaderView.prototype.template = _.template(t);

      /*events:
        "click": "hide"
      */


      HeaderView.prototype.render = function() {
        return this.$el.find("#page-title").html(this.template(this.model.toJSON()));
      };

      HeaderView.prototype.hide = function(e) {
        var that, time;
        that = this;
        time = e !== void 0 ? 1000 : 0;
        return this.$el.animate({
          "margin-top": "-50"
        }, time, function() {
          that.delegateEvents({
            "click": "show"
          });
          return that.createButton();
        });
      };

      HeaderView.prototype.show = function(e) {
        var that;
        that = this;
        return this.$el.animate({
          "margin-top": "0"
        }, 1000, function() {
          return that.delegateEvents({
            "click": "hide"
          });
        });
      };

      HeaderView.prototype.createButton = function() {
        return console.log(this.$el.find(".row").find("div").first());
      };

      return HeaderView;

    })(Backbone.View);
  });

}).call(this);
