// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['text!templates/lang.html', 'collections/langs', 'langs'], function(template, LangsCollection, langs) {
    var LangView, _ref;
    return LangView = (function(_super) {
      __extends(LangView, _super);

      function LangView() {
        _ref = LangView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      LangView.prototype.el = "#lang-container";

      LangView.prototype.template = _.template(template);

      LangView.prototype.events = {
        "click .lang": "changeLang",
        "mouseover .lang": "overLang",
        "mouseOut .lang": "outLang"
      };

      LangView.prototype.initialize = function(app) {
        this.collection = new LangsCollection(app.langs);
        return this.render;
      };

      LangView.prototype.render = function() {
        var that;
        that = this;
        _.each(this.collection.models, function(item) {
          return that.$el.append(that.template(item.toJSON()));
        });
        return this;
      };

      LangView.prototype.changeLang = function(event) {
        return this.activate($(event.target));
      };

      LangView.prototype.overLang = function(e) {
        return $(e.target).fadeTo(200, 1);
      };

      LangView.prototype.outLang = function(e) {
        return $(e.target).fadeTo(200, 0.5);
      };

      LangView.prototype.activate = function(el) {
        this.deactivate();
        return el.addClass("circle");
      };

      LangView.prototype.deactivate = function() {
        this.$el.find(".circle").removeClass("circle");
        return this;
      };

      return LangView;

    })(Backbone.View);
  });

}).call(this);

/*
//@ sourceMappingURL=lang.map
*/
