// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['text!templates/page.html'], function(template) {
    var PageTitleView, _ref;
    return PageTitleView = (function(_super) {
      __extends(PageTitleView, _super);

      function PageTitleView() {
        _ref = PageTitleView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      PageTitleView.prototype.el = ".page-title-container";

      PageTitleView.prototype.template = _.template(template);

      PageTitleView.prototype.render = function() {
        var p, that;
        that = this;
        p = this.$el.find("p").first();
        if (p.html() !== void 0) {
          return p.animate({
            "margin-left": "-2000px"
          }, 1000, function() {
            that.$el.html(that.template(that.model.toJSON()));
            return that.show();
          });
        } else {
          this.$el.html(this.template(this.model.toJSON()));
          return this.show();
        }
      };

      PageTitleView.prototype.hide = function() {
        var p;
        p = this.$el.find("p").first();
        if (p.html() !== void 0) {
          return p.animate({
            "margin-left": "-2000px"
          }, 500);
        }
      };

      PageTitleView.prototype.show = function() {
        var p;
        p = this.$el.find("p").first();
        if (p.html() !== void 0) {
          return p.animate({
            "margin-right": "0px"
          }, 500);
        }
      };

      return PageTitleView;

    })(Backbone.View);
  });

}).call(this);
