// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['models/page', 'text!templates/page_content.html'], function(PageModel, template) {
    var PageContainer, _ref;
    return PageContainer = (function(_super) {
      __extends(PageContainer, _super);

      function PageContainer() {
        _ref = PageContainer.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      PageContainer.prototype.el = ".page-container";

      PageContainer.prototype.tagName = "div";

      PageContainer.prototype.className = "look";

      PageContainer.prototype.initialize = function() {
        this.model = new PageModel;
        return this.$el.find("#page_content").val('');
      };

      PageContainer.prototype.setTpl = function(t) {
        var tpl;
        tpl = _.template(t);
        return this.model.set({
          html: tpl()
        });
      };

      PageContainer.prototype.renderPage = function() {
        return this.$el.html(this.template(this.model.toJSON()));
      };

      PageContainer.prototype.render = function() {
        this.model.set({
          html: this.page()
        });
        this.renderPage();
        return this.$el.find('a').attr('target', '_blank');
      };

      return PageContainer;

    })(Backbone.View);
  });

}).call(this);
