// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['models/page', 'text!templates/page_content.html'], function(PageModel, template) {
    var PageContainer, _ref;
    return PageContainer = (function(_super) {
      __extends(PageContainer, _super);

      function PageContainer() {
        _ref = PageContainer.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      PageContainer.prototype.el = ".page-container";

      PageContainer.prototype.tagName = "div";

      PageContainer.prototype.className = "look";

      PageContainer.prototype.page = _.template("");

      PageContainer.prototype.initialize = function() {
        this.model = new PageModel;
        return this.$el.find("#page_content").val('');
      };

      PageContainer.prototype.renderPage = function() {
        return this.$el.html(this.template(this.model.toJSON()));
      };

      PageContainer.prototype.render = function() {
        return this.setPage(this.pageFile);
      };

      PageContainer.prototype.setPage = function(pageFile) {
        var locale, returnPage, that;
        that = this;
        locale = Locale.locale.toJSON().link;
        returnPage = "";
        return require(["mdown!pages/" + locale + "/" + pageFile + ".md"], function(page) {
          var model;
          returnPage = _.template(page);
          model = new PageModel({
            html: returnPage()
          });
          that.$el.html(that.template(model.toJSON()));
          return that.$el.find('a').attr('target', '_blank');
        });
      };

      return PageContainer;

    })(Backbone.View);
  });

}).call(this);
