// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['text!templates/page.html'], function(template) {
    var PageTitleView, _ref;
    return PageTitleView = (function(_super) {
      __extends(PageTitleView, _super);

      function PageTitleView() {
        _ref = PageTitleView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      PageTitleView.prototype.el = $(".page-title-container");

      PageTitleView.prototype.template = _.template(template);

      PageTitleView.prototype.render = function() {
        return this.$el.html(this.template(this.model.toJSON()));
      };

      return PageTitleView;

    })(Backbone.View);
  });

}).call(this);
