// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['models/page', 'text!templates/page_content.html', 'mdown!pages/php.md', 'views/page_container'], function(PageModel, template, php, PageContainer) {
    var PHPView, _ref;
    return PHPView = (function(_super) {
      __extends(PHPView, _super);

      function PHPView() {
        _ref = PHPView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      PHPView.prototype.el = ".page-container";

      PHPView.prototype.tagName = "div";

      PHPView.prototype.className = "look";

      PHPView.prototype.template = _.template(template);

      PHPView.prototype.initialize = function() {
        this.model = new PageModel;
        return this.$el.find("#page_content").val('');
      };

      PHPView.prototype.render = function() {
        var tpl;
        tpl = _.template(php);
        this.model.set({
          html: tpl()
        });
        return this.$el.html(this.template(this.model.toJSON()));
      };

      return PHPView;

    })(Backbone.View);
  });

}).call(this);
