// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["text!templates/quality.html"], function(template) {
    var QualityView, _ref;
    return QualityView = (function(_super) {
      __extends(QualityView, _super);

      function QualityView() {
        _ref = QualityView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      QualityView.prototype.template = _.template(template);

      QualityView.prototype.render = function() {
        this.$el.html(this.template(this.model.toJSON()));
        return this;
      };

      return QualityView;

    })(Backbone.View);
  });

}).call(this);
