// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['models/background'], function(BackgroundModel) {
    var BackgroundsCollection, _ref;
    return BackgroundsCollection = (function(_super) {
      __extends(BackgroundsCollection, _super);

      function BackgroundsCollection() {
        _ref = BackgroundsCollection.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      BackgroundsCollection.prototype.model = BackgroundModel;

      return BackgroundsCollection;

    })(Backbone.Collection);
  });

}).call(this);
