// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['models/lang'], function(LangModel) {
    var LangsCollection, _ref;
    return LangsCollection = (function(_super) {
      __extends(LangsCollection, _super);

      function LangsCollection() {
        _ref = LangsCollection.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      LangsCollection.prototype.model = LangModel;

      return LangsCollection;

    })(Backbone.Collection);
  });

}).call(this);

/*
//@ sourceMappingURL=langs.map
*/
