// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["models/quality"], function(QualityModel) {
    var QualityCollection, _ref;
    return QualityCollection = (function(_super) {
      __extends(QualityCollection, _super);

      function QualityCollection() {
        _ref = QualityCollection.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      QualityCollection.prototype.model = QualityModel;

      return QualityCollection;

    })(Backbone.Collection);
  });

}).call(this);
