// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var backgrounds;
    return backgrounds = [
      {
        url: "/images/fon.png"
      }, {
        url: "/images/fon1.png"
      }, {
        url: "/images/textusr5.png",
        active: true
      }, {
        url: "/images/textusr6.png"
      }, {
        url: "/images/textusr7.png"
      }
    ];
  });

}).call(this);
