// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var skills;
    skills = [
      {
        name: "me",
        src: "look-me",
        link: "about-me",
        page_title: "Обо мне",
        thumbnail: "/images/man.png",
        background: "",
        w: 128,
        h: 128,
        quality: [
          {
            title: "Усидчивость"
          }, {
            title: "Трудолюбие"
          }, {
            title: "Обучаемость"
          }, {
            title: "Коммуникабельность"
          }, {
            title: "Работа в комманде"
          }, {
            title: "DRY"
          }
        ]
      }, {
        name: "php",
        src: "look-php",
        link: "php",
        page_title: "Мои PHP-навыки",
        thumbnail: "/images/php.png",
        background: "",
        w: 128,
        h: 100,
        quality: [
          {
            title: "Symfony 2"
          }, {
            title: "Doctrine"
          }, {
            title: "Composer"
          }, {
            title: "Объектно-ориентированное программирование"
          }, {
            title: "Smarty"
          }, {
            title: "Модель-Представление-Контроллер"
          }, {
            title: "Kohana"
          }, {
            title: "Laravel"
          }, {
            title: "Code Ingniter"
          }, {
            title: "Zend Framework"
          }, {
            title: "Doctrine Mongoose-ODM"
          }, {
            title: "Шаблоны проектирования"
          }, {
            title: "SimpleHTMLDom"
          }, {
            title: "PHPExcel"
          }
        ]
      }, {
        name: "database",
        src: "look-database",
        link: "database",
        page_title: "Знания баз данных",
        thumbnail: "/images/database.png",
        background: "",
        w: 100,
        h: 100,
        quality: [
          {
            title: "Mysql"
          }, {
            title: "MongoDB"
          }
        ]
      }, {
        name: "node",
        src: "look-node",
        link: "node.js",
        page_title: "Изучение Node.JS",
        thumbnail: "/images/node.png",
        background: "",
        w: 128,
        h: 128,
        quality: [
          {
            title: "ExpressJS"
          }, {
            title: "Socket.IO"
          }, {
            title: "Mongoose"
          }, {
            title: "Jade"
          }, {
            title: "Создание REST API"
          }
        ]
      }, {
        name: "javascript",
        src: "look-js",
        link: "javascript",
        page_title: "Javascript. Светлое будующее",
        thumbnail: "/images/javascript.png",
        background: "",
        w: 100,
        h: 100,
        quality: [
          {
            title: "JQuery"
          }, {
            title: "BackboneJS"
          }, {
            title: "RequireJS"
          }, {
            title: "CoffeeScript"
          }
        ]
      }, {
        name: "linux",
        src: "look-linux",
        link: "linux",
        page_title: "Использование Linux",
        thumbnail: "/images/ubuntu.png",
        background: "",
        w: 100,
        h: 100,
        quality: [
          {
            title: "unix-console"
          }
        ]
      }, {
        name: "git",
        src: "look-git",
        link: "git",
        page_title: "Использование системы контролля версий",
        thumbnail: "/images/git.png",
        background: "",
        w: 100,
        h: 100,
        quality: [
          {
            title: "Github"
          }, {
            title: "Bitbucket"
          }
        ]
      }, {
        name: "portfolio",
        src: "portfolio-look",
        link: "portfolio",
        page_title: "Мое портфолио",
        background: "",
        w: 100,
        h: 100,
        quality: [
          {
            title: "flvto.com"
          }, {
            title: "olyrics.com"
          }, {
            title: "britanium.com"
          }
        ]
      }, {
        name: "contacts",
        src: "contacts-look",
        link: "contact-me",
        page_title: "Мои контакты",
        thumbnail: "/images/contacts.png",
        background: "",
        w: 100,
        h: 100,
        quality: [
          {
            title: "Обратная связь"
          }
        ]
      }
    ];
    _.templateSettings = {
      interpolate: /\{\{(.+?)\}\}/g
    };
    return skills;
  });

}).call(this);
