// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var langs;
    return langs = [
      {
        locale: "RU",
        link: "ru"
      }, {
        locale: "EN",
        link: "en"
      }
    ];
  });

}).call(this);

/*
//@ sourceMappingURL=langs.map
*/
