// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var locales;
    return locales = [
      {
        locale: "RU",
        link: "ru",
        active: true
      }, {
        locale: "EN",
        link: "en"
      }
    ];
  });

}).call(this);
