// Generated by CoffeeScript 1.6.3
(function() {
  requirejs.config({
    baseUrl: 'js',
    paths: {
      text: 'lib/text',
      markdownConverter: 'lib/requirejs-plugins/lib/Markdown.Converter',
      mdown: 'lib/requirejs-plugins/src/mdown'
    },
    shim: {
      'lib/underscore-min': {
        exports: '_'
      },
      'lib/backbone-min': {
        deps: ['lib/underscore-min'],
        exports: 'Backbone'
      },
      'resume': {
        deps: ['lib/underscore-min', 'lib/backbone-min']
      }
    }
  });

  require(["resume"], function(BabenkoResume) {
    window.BabenkoResume = new BabenkoResume();
    $('body').find(".skill-container").find('img').first().click().addClass('opacity-100');
    return hljs.initHighlighting();
  });

}).call(this);
