// Generated by CoffeeScript 1.6.3
(function() {
  requirejs.config({
    baseUrl: 'js',
    paths: {
      text: 'lib/text'
    },
    shim: {
      'lib/underscore-min': {
        exports: '_'
      },
      'lib/backbone-min': {
        deps: ['lib/underscore-min'],
        exports: 'Backbone'
      },
      'resume': {
        deps: ['lib/underscore-min', 'lib/backbone-min']
      }
    }
  });

  require(["resume"], function(BabenkoResume) {
    window.BabenkoResume = new BabenkoResume();
    return $('body').find(".skill-container").first().click();
  });

}).call(this);
