// Generated by CoffeeScript 1.6.3
(function() {
  define(["config", "locales", "views/resume", "views/locale", "controller"], function(config, locales, ResumeView, LocaleView, ResumeController) {
    var BabenkoResume;
    return BabenkoResume = (function() {
      BabenkoResume.prototype.skills = {};

      function BabenkoResume() {
        var locale, resume;
        this.skills = config;
        this.locales = locales;
        this.controller = new ResumeController();
        resume = new ResumeView(this);
        resume.render();
        locale = new LocaleView(this);
        locale.render();
        Backbone.history.start();
      }

      return BabenkoResume;

    })();
  });

}).call(this);
