// Generated by CoffeeScript 1.6.3
(function() {
  define(["config", "views/resume", "views/lang", "controller", "langs"], function(config, ResumeView, LangView, ResumeController, langs) {
    var BabenkoResume;
    return BabenkoResume = (function() {
      BabenkoResume.prototype.skills = {};

      function BabenkoResume() {
        var lang, resume;
        this.skills = config;
        this.langs = langs;
        this.controller = new ResumeController();
        resume = new ResumeView(this);
        resume.render();
        lang = new LangView(this);
        lang.render();
        Backbone.history.start();
      }

      return BabenkoResume;

    })();
  });

}).call(this);

/*
//@ sourceMappingURL=resume.map
*/
