// Generated by CoffeeScript 1.6.3
(function() {
  define(["config", "locales", "backgrounds", "views/resume", "views/locale", "views/background", "controller"], function(config, locales, backgrounds, ResumeView, LocaleView, Background, ResumeController) {
    var BabenkoResume;
    return BabenkoResume = (function() {
      BabenkoResume.prototype.skills = {};

      function BabenkoResume() {
        this.skills = config;
        this.locales = locales;
        this.backgrounds = backgrounds;
        this.controller = new ResumeController(this);
        this.resume = new ResumeView({
          app: this
        });
        window.Locale = new LocaleView(this);
        Locale.render();
        window.BackgoundView = new Background(this);
        BackgoundView.render();
        this.resume.render();
        Backbone.history.start();
      }

      return BabenkoResume;

    })();
  });

}).call(this);
