// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define([], function() {
    var BackgroundModel, _ref;
    return BackgroundModel = (function(_super) {
      __extends(BackgroundModel, _super);

      function BackgroundModel() {
        _ref = BackgroundModel.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      BackgroundModel.prototype.defaults = {
        url: "/images/textusr5.png",
        active: false
      };

      return BackgroundModel;

    })(Backbone.Model);
  });

}).call(this);
