// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define([], function() {
    var QualityModel, _ref;
    return QualityModel = (function(_super) {
      __extends(QualityModel, _super);

      function QualityModel() {
        _ref = QualityModel.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      QualityModel.prototype.defaults = {
        title: "",
        img: "",
        w: 128,
        h: 128
      };

      return QualityModel;

    })(Backbone.Model);
  });

}).call(this);
