// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['text!templates/page_content.html', 'mdown!pages/vcs.md', 'views/page_container'], function(template, git, PageContainer) {
    var GitView, _ref;
    return GitView = (function(_super) {
      __extends(GitView, _super);

      function GitView() {
        _ref = GitView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      GitView.prototype.template = _.template(template);

      GitView.prototype.page = _.template(git);

      return GitView;

    })(PageContainer);
  });

}).call(this);
