// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['text!templates/page_content.html', 'mdown!pages/linux.md', 'views/page_container'], function(template, linux, PageContainer) {
    var LinuxView, _ref;
    return LinuxView = (function(_super) {
      __extends(LinuxView, _super);

      function LinuxView() {
        _ref = LinuxView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      LinuxView.prototype.template = _.template(template);

      LinuxView.prototype.page = _.template(linux);

      return LinuxView;

    })(PageContainer);
  });

}).call(this);
